### ISSUE TITLE
BOTW config should have a file selector

### ISSUE THREAD

**Issue by 5685C4A059D5** [WerWolv98/EdiZon_ConfigsAndScripts#25]
There are 6 files in directories 0 through 5, it would be better if it's possible to select which one to edit.
Or at least default it to file 0, which (I think) is the manual save file.

**Comment by buitim** [comment]
Personally, I just opened up the json and tried changing it to empty quotes. That didn't work. Save 1 should be the manual save (Save 0 is the autosave), so I just changed it to that. Gonna play around with it and see if there's a way around that.

**Comment by maciak** [comment]
save 3 is manual one and that's how it's set up now to open a manual save.

**Comment by 5685C4A059D5** [comment]
I guess it's different for everyone. My manual save is 0.

**Comment by maciak** [comment]
From what I've noticed it's always 3. Maybe your autosave 0 was made right after manual one.

**Comment by 5685C4A059D5** [comment]
It's definitely 0 for me.
It's always 0 regardless of the save time of the files.

**Comment by buitim** [comment]
This might be a potential solution? I looked at the docs (currently playing around with Golf Story but can't load saves 😅) and found the use of "\\\d". Not sure if this is a RegEx thing (not too familiar with it) but it seems to bring up all of my saves. Find the line `	"saveFilePaths": ["x"],` where 'x' is an int representing your save slot. Replace the x with "\\\d" so that it ends up looking like this: `	"saveFilePaths": ["\\d"],`

Let me know if this works! Now on to finding out how to get step size working...

**Comment by maciak** [comment]
Yep that did it. I can now scroll through all save files.

**Comment by billzhong** [comment]
3 is not the manual save for me. 👍 for file selector.
